version: '3.8'

services:
    flask_app:
        image: ${DOCKER_REGISTRY}/product-tags:latest
        build: ./app
        restart: unless-stopped
        container_name: product-tags
        ports:
            - 4444:4444